// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
#pragma warning disable 1591, 3008, 3009, 0108
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC
{
    public class SharedController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _Layout = "_Layout";
            }
            public readonly string _Layout = "~/Views/Shared/_Layout.cshtml";
            static readonly _ErrorClass s_Error = new _ErrorClass();
            public _ErrorClass Error { get { return s_Error; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _ErrorClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string _Error = "_Error";
                }
                public readonly string _Error = "~/Views/Shared/Error/_Error.cshtml";
            }
            static readonly _LoginClass s_Login = new _LoginClass();
            public _LoginClass Login { get { return s_Login; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _LoginClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string _LoginPage = "_LoginPage";
                    public readonly string _User = "_User";
                }
                public readonly string _LoginPage = "~/Views/Shared/Login/_LoginPage.cshtml";
                public readonly string _User = "~/Views/Shared/Login/_User.cshtml";
            }
            static readonly _TodoClass s_Todo = new _TodoClass();
            public _TodoClass Todo { get { return s_Todo; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _TodoClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string _DeleteItem = "_DeleteItem";
                    public readonly string _Details = "_Details";
                    public readonly string _Search = "_Search";
                    public readonly string _Statuses = "_Statuses";
                    public readonly string _Todo = "_Todo";
                }
                public readonly string _DeleteItem = "~/Views/Shared/Todo/_DeleteItem.cshtml";
                public readonly string _Details = "~/Views/Shared/Todo/_Details.cshtml";
                public readonly string _Search = "~/Views/Shared/Todo/_Search.cshtml";
                public readonly string _Statuses = "~/Views/Shared/Todo/_Statuses.cshtml";
                public readonly string _Todo = "~/Views/Shared/Todo/_Todo.cshtml";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108
